In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[8,9,10],[12,11,13]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 11, 13]])

In [5]:
a = arr.flatten()

In [12]:
a[0]

np.int64(1)

In [7]:
a[3:]

array([ 4,  5,  6,  8,  9, 10, 12, 11, 13])

In [8]:
a[:8]

array([1, 2, 3, 4, 5, 6, 8, 9])

In [9]:
a[::2]

array([ 1,  3,  5,  8, 10, 11])

In [10]:
a[::3]

array([ 1,  4,  8, 12])

In [11]:
b = a[3:8]

In [13]:
b

array([4, 5, 6, 8, 9])

In [15]:
b = a[2:10].copy()

In [16]:
b


array([ 3,  4,  5,  6,  8,  9, 10, 12])

In [17]:
b[1] = 20

In [18]:
print(b[1] , a)

20 [ 1  2  3  4  5  6  8  9 10 12 11 13]


In [19]:
idx=[3,4,10]
print(a[idx])

[ 4  5 11]


In [20]:
print(a[a>10])

[12 11 13]


In [21]:
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [22]:
#question
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a1 = np.array([1.1,2.5,3.7])
a1

array([1.1, 2.5, 3.7])

In [24]:
a1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [25]:
print(arr[arr%2==0])

[2 4 6 8]


In [26]:
a2 = np.array([1,2,3,4,5,6,7,8,9])
a2.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a3 = np.array([1,2,45,65,76,74,34,54,90])
print(a3[a3>50])

[65 76 74 54 90]
