In [1]:
import numpy as np
arr = np.array([1,2,3])

In [2]:
arr

array([1, 2, 3])

In [3]:
np.array([[1,2,3],[4,5,6],[6,7,8]])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a.shape

(3, 3)

In [18]:
type(a)

numpy.ndarray

In [20]:
a.size

9

In [21]:
a.ndim

2

In [22]:
a.dtype

dtype('int64')

In [23]:
 arr2 = a.astype(np.float32)

In [24]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [25]:
arr2.reshape((1,9))

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)

In [26]:
a.flatten()
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a.flatten()
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr1 = a.flatten()
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])